### ISSUE TITLE
Can I use this tool for rapid-fire http posting?

### ISSUE THREAD

**Issue by cjgd** [proactiveRISK/switchblade#4]
_From [apb...@gmail.com](https://code.google.com/u/103767539706636845149/) on July 01, 2011 23:01:50_

Well, obviously I can, but I need to have an exact request. No useragent, only
Random header: X8lL3Y1o95S2SOarEKMY0P2YDrZruFeJxwKpYiqk
Content-Length: 0
Connection: keep-alive

as well as a specific url.

_Original issue: http://code.google.com/p/owasp-dos-http-post/issues/detail?id=4_

**Comment by sudofox** [comment]
wait what is this? I used to own austinburk.com, let it expire a long time ago, and registered it again recently... what was I doing here six years ago haha
